name: Deploy Infra with Terraform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TF_WORKING_DIR: ./infra

jobs:
  terraform:
    name: Terraform CI/CD Pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Secret management
    - name: Configure cloud credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      run: echo "Cloud credentials configured"

    # Terraform Setup
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0


    # Format Check
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    # Init
    - name: Terraform Init
      run: terraform init -input=false

    # Validation
    - name: Terraform Validate
      run: terraform validate


    # Plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan

    # Apply
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -input=false tfplan

    # Report Status
    - name: Notify Deployment Status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Terraform deployment succeeded"
        else
          echo "❌ Terraform deployment failed"
        fi
