# This is a basic workflow to help you get started with Actions

name: Despliegue_Terraform


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:

  Terraform_build:
  
    name: Terraform CI/CD Pipeline
    runs-on: ubuntu-latest


    steps: 
      - uses: actions/checkout@v4
      
      - name: Configure cloud credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "Cloud credentials configured"



      - name: Run a one-line script
        run: echo Hello, world!

 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
